version: '3.8'

services:
    backend:
        build: .
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
            - BITRIX_CLIENT_ID=local.6840f32c4595b6.11637008
            - BITRIX_CLIENT_SECRET=RWwFsClBMjCBns7r63TPu9Pl6o4yRncrv7Ef3W0XothoPqcNpa
            - FRONTEND_URL=http://localhost:3000
            - DATABASE_URI=mongodb://mongo:27017/OauthBitrix24
            - ALLOWED_ORIGINS=http://localhost:3000,https://client-oauth-bitrix24.vercel.app
            - JWT_SECRET=i_want_to_work_at_AASC
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mongo

    mongo:
        image: mongo:6.0 # hoặc phiên bản bạn cần
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
