version: '3.8'

services:
    backend:
        build: .
        ports:
            - '8080:5000'
        environment:
            - PORT=8080
            - BITRIX_CLIENT_ID=local.6840f32c4595b6.11637008
            - BITRIX_CLIENT_SECRET=RWwFsClBMjCBns7r63TPu9Pl6o4yRncrv7Ef3W0XothoPqcNpa
            - FRONTEND_URL=http://localhost:3000
            - DATABASE_URI=mongodb+srv://xlehieu:Hieumao2003@cluster0.uwnpg.mongodb.net/OAuthBitrix?retryWrites=true&w=majority&appName=Cluster0
            - ALLOWED_ORIGINS=http://localhost:3000,https://client-oauth-bitrix24.vercel.app
            - JWT_SECRET=i_want_to_work_at_AASC
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
